name: Production Deploy

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
    
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
      - name: Install Dependencies
        run: npm install

      - name: Lint Stage
        run: npm run lint

      - name: Test Stage
        run: npm run test

  deploy:
    name: Deploy App to Fly.io
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
